### ISSUE TITLE
Update for 1.21?

### ISSUE THREAD

**Issue by FaultyFunctions** [dbrighthd/gendermodspigot#2]
One of my player's has the 1.21 version of the mod installed and we have the latest plugin installed on our server but they are getting this error every time they try to login:
![image](https://github.com/user-attachments/assets/90bedb11-7d4f-4ca7-9155-8e30469a9718)

**Comment by LcyDev** [comment]
+bump

**Comment by Stigstille** [comment]
Sorry for the wait, I just saw the issue. I will be attempting to update the plugin soon^^

Will keep you updated

**Comment by Stigstille** [comment]
I will be testing winpixie's PR tomorrow. The updated version should be on the modrinth as soon as I verify everything is working correctly ^^

**Comment by Stigstille** [comment]
WinnPixie's PR has been pulled, and the update is now on modrinth!
GLHF!!
