### ISSUE TITLE
1.20.6 kick players from server

### ISSUE THREAD

**Issue by szarkans** [dbrighthd/gendermodspigot#3]
IDK why...

![image](https://github.com/user-attachments/assets/93b36095-1832-41d7-a104-f69ffecc4f6c)

![image](https://github.com/user-attachments/assets/a01e4456-c1bf-4dd6-afc3-decc82776e4d)

**Comment by Stigstille** [comment]
Seems to be the same as #2

**Comment by Stigstille** [comment]
WinnPixie's PR has been pulled, and the update is now on modrinth!
GLHF!!
